### ISSUE TITLE
Feature Request: Item Displays

### ISSUE THREAD

**Issue by hapyl** [eszesbalint/bdstudio#10]
**Amazing tool!**

Though I would love to see item displays in addition to blocks if possible. Sometimes all I'm missing is couple of items, but editing them by hand is pain. Same can be said about text displays, but they are not that hard to add manually.

Also would love to have ability to switch between Minecraft translation and raw matrix.

**Comment by eszesbalint** [comment]
Item displays are coming in the next release soon (in a few days)

**Comment by eszesbalint** [comment]
Added in Beta 1.2
