### ISSUE TITLE
Mob heads and banners don't display proprely

### ISSUE THREAD

**Issue by FeatherSlowfall** [eszesbalint/bdstudio#11]
Mob and player heads along with banners  are not displayed as their actual items but rather as a placeholder item.

**Comment by FeatherSlowfall** [comment]
Would also like to say thank you for this amazing tool! Ever since the display entities released i've been looking for a way to mess around with them and this just perfect!, keep up the great work!

**Comment by eszesbalint** [comment]
That's a feature, not a bug. The why is already answered in #4 . But in short, those models are not in the Minecraft assets folder, they're hard coded into the game itself, so I have no way to extract them. I would have to recreate those models manually, and that's a tedious task for 100+ models. Hence the placeholder.

**Comment by FeatherSlowfall** [comment]
Oh i see, well i'd recommend you just put a placeholder item that is more akin to the items shape, like an 8x8 square for the player head and just the base banner model for the banners because the main reason it'd be usefull is for positioning

**Comment by histefanhere** [comment]
I knew this issue was going to come up as soon as I proposed the fix haha, I was thinking a dialogue could come up informing the user that it's not possible to get exact models, or to have a rough shape of the blocks as feather said, or ideally both.
