### ISSUE TITLE
Command imports incorrectly

### ISSUE THREAD

**Issue by AuroraHydroid** [eszesbalint/bdstudio#17]
I attempted to summon a model into my world, and the lower amethyst and the fence came in incorrectly. I've included screenshots below and the code I used to summon it. (Yes, the magma block is supposed to be at that level) Thank you in advance!

![2023-07-01_21 32 02](https://github.com/eszesbalint/bdstudio/assets/77693193/23c72dc7-6954-4a0a-8d60-c4d92a256e6a)
![image](https://github.com/eszesbalint/bdstudio/assets/77693193/ee328dd0-cc2a-420d-8e2e-7a2bcc8bf24d)

`execute at @e[type=armor_stand, tag=amethyst_statue] run summon block_display ~-0.5 ~ ~-0.5 {Passengers:[{id:"minecraft:block_display",block_state:{Name:"minecraft:amethyst_cluster",Properties:{facing:"up"}},transformation:[1.0000f,0.0000f,0.0000f,0.0000f,0.0000f,1.0000f,0.0000f,1.2500f,0.0000f,0.0000f,1.0000f,0.0125f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:amethyst_cluster",Properties:{facing:"up"}},transformation:[1.0000f,0.0000f,0.0000f,0.0000f,0.0000f,1.0000f,0.0000f,1.6875f,0.0000f,0.0000f,1.0000f,0.0125f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:amethyst_cluster",Properties:{}},transformation:[0.7000f,0.0000f,0.0000f,0.1875f,0.0000f,0.7000f,0.0000f,0.5625f,0.0000f,0.0000f,0.7000f,0.1875f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{up:"true",east:"low",south:"low"}},transformation:[0.5000f,0.0000f,0.0000f,-0.1250f,0.0000f,0.5000f,0.0000f,0.0000f,0.0000f,0.0000f,0.5000f,-0.1250f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{up:"true",east:"low",south:"low"}},transformation:[-0.0000f,0.0000f,0.5000f,-0.1250f,0.0000f,0.5000f,0.0000f,0.0000f,-0.5000f,0.0000f,-0.0000f,1.1250f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{east:"low"}},transformation:[-0.0000f,0.0000f,0.5000f,-0.1250f,0.0000f,0.5000f,0.0000f,0.0000f,-0.5000f,0.0000f,-0.0000f,0.8750f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{up:"true",east:"low",south:"low"}},transformation:[-0.5000f,0.0000f,0.0000f,1.1250f,0.0000f,0.5000f,0.0000f,0.0000f,-0.0000f,0.0000f,-0.5000f,1.1250f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{up:"true",east:"low",south:"low"}},transformation:[0.0000f,0.0000f,-0.5000f,1.1250f,0.0000f,0.5000f,0.0000f,0.0000f,0.5000f,0.0000f,0.0000f,-0.1250f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{east:"low"}},transformation:[0.0000f,0.0000f,-0.5000f,1.1250f,0.0000f,0.5000f,0.0000f,0.0000f,0.5000f,0.0000f,0.0000f,0.1250f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{east:"low"}},transformation:[0.5000f,0.0000f,0.0000f,0.1250f,0.0000f,0.5000f,0.0000f,0.0000f,0.0000f,0.0000f,0.5000f,0.6250f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:blackstone_wall",Properties:{east:"low"}},transformation:[0.5000f,0.0000f,0.0000f,0.1250f,0.0000f,0.5000f,0.0000f,0.0000f,0.0000f,0.0000f,0.5000f,-0.1250f,0.0000f,0.0000f,0.0000f,1.0000f]},{id:"minecraft:block_display",block_state:{Name:"minecraft:magma_block",Properties:{}},transformation:[0.7000f,0.0000f,0.0000f,0.1250f,0.0000f,0.7000f,0.0000f,-0.5000f,0.0000f,0.0000f,0.7000f,0.1250f,0.0000f,0.0000f,0.0000f,1.0000f]}]}`

**Comment by eszesbalint** [comment]
Fixed in Beta 1.2.2
