### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by Danik4ek** [eszesbalint/bdstudio#23]
Maybe I'm just stupid, but it would be cool if you could set up a collision. that is, for example, I made a hut and I would not want to be able to go into it through the wall. That is, do not make a custom collision (although it would be cool, but just a cubic collision to prevent it from passing through

**Comment by SBtree-bit** [comment]
You cannot do this. The best you can do is either using blocks to set collision, or to use invisible shulkers (whose collision cannot be changed from a full block).
