### ISSUE TITLE
Can't add certain blocks (TypeError: n.elements is not iterable)

### ISSUE THREAD

**Issue by histefanhere** [eszesbalint/bdstudio#4]
Hello, amazing webapp! Will definitely be following development.

Attempting to place certain blocks produces the following error in the log:

```
index-97e9410d.js:3472 Uncaught (in promise) TypeError: n.elements is not iterable
    at _r (index-97e9410d.js:3472:6337)
    at async ii.updateModel (index-97e9410d.js:3472:3026)
_r @ index-97e9410d.js:3472
await in _r (async)
set blockState @ index-97e9410d.js:3472
execute @ index-97e9410d.js:3472
add @ index-97e9410d.js:3912
add @ index-97e9410d.js:3912
(anonymous) @ index-97e9410d.js:3478
index-97e9410d.js:3912 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'selected')
    at Object.add (index-97e9410d.js:3912:8656)
add @ index-97e9410d.js:3912
await in add (async)
(anonymous) @ index-97e9410d.js:3478
```

The following blocks I've tried and seem to be affected:
- All bed colours
- All chest types
- All normal, wall, and hanging signs

**Comment by histefanhere** [comment]
Actually I tried a few more, and it seems all head types and liquids are affected as well, so this is probably what #3 is referring to

**Comment by eszesbalint** [comment]
Ooops, that's my bad. Unloadable blockstates should've been removed in Beta 1.1.1, I just haven't updated the blockstate list file on the web.

The reason those blocks can't be loaded is that they are not stored in the minecraft assets folder, so I have no way of extracting a model of it, they are hard-coded into the game itself. The solution would be to recreate those blockstates in Blockbench, but I just don't have the capacity right now to model 100+ different blocks.

**Comment by histefanhere** [comment]
One possible idea is to display some generic texture in bdstudio because they do actually work when you run the command in game

**Comment by eszesbalint** [comment]
That's a great a idea! I will add a placeholder model for those blockstates. Thanks for your suggestion!
