### ISSUE TITLE
Tag may be added. (Sorry if there are mistakes in the article, it is being translated from Turkish to English)

### ISSUE THREAD

**Issue by ege78pro** [eszesbalint/bdstudio#8]
I want to rotate models while in game,
but I can't rotate it because there is no tag, so tag should be added.

The site should add the same tag to each part,
We can't rotate the model if it just adds it to the body.

It is difficult to add them one by one.

**Comment by eszesbalint** [comment]
If you add an NBT tag for the project itself, then all block displays in it will inherit those tags. Deselect all block displays, then under the Properties tab you can add those tags.

**Comment by ege78pro** [comment]
I know I can add it from the properties tab, but I don't want to add them all one by one.

if we apply the same nbt to all of them, we can rotate `execute as @e[nbt=(nbt tag)] at @s run tp @s ~ ~ ~ ~90 ~` using this command

**Comment by ege78pro** [comment]
thanks i didn't know that.
